spring:
  application:
    name: full-stack-app
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: ErhGcvNnxJVPNQoYNxcABLJJjXTKtjNn
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
  error:
    include-message: always
